### ISSUE TITLE
snr estimate

### ISSUE THREAD

**Issue by rainskyfyy** [chenwj1989/python-speech-enhancement#3]
what are #1~#5 mean in the 75~79 lines of file "pns/noise_suppressor.py"?
like this:
            #1 rough noise estimation
            #2 rough a priori and posteri snr estimation
            #3 speech presence prabability estimation
            #4 precise noise estimation
            #5 a priori and posteri snr estimation
 I only see codes of condition "fnz_flag==1" here. Are you going to accomplish them in the future?
Actually, I want to do snr estimate with your code in this project. could you please tell me how I can do the calculation? Thanks !!!

**Comment by SouppuoS** [comment]
hi @rainskyfyy 
I think `#1~5` is implemented in `noise_estimator` (line 82), which are the steps of IMCRA.

**Comment by chenwj1989** [comment]
Hi @rainskyfyy , sorry I've not very active on github for a while. 

The nosie estimation is implemented in noise_estimator.py.  
Please refer to Cohen's papers for more details on noise estimation.
I. Cohen and B. Berdugo, [Speech Enhancement for Non-Stationary Noise Environments](https://israelcohen.com/wp-content/uploads/2018/05/sp_Nov2001.pdf), Signal Processing, Vol. 81, No. 11, Nov. 2001, pp. 2403-2418.
I. Cohen, [Noise Spectrum Estimation in Adverse Environments: Improved Minima Controlled Recursive Averaging](https://israelcohen.com/wp-content/uploads/2018/05/SAP_Sep2003.pdf), IEEE Trans. Speech and Audio Processing, Vol. 11, No. 5, Sep. 2003, pp. 466-475.

Thank you @SouppuoS  for the reply.
